import {EducationTypes} from "../definitions/types";

export const educationData: EducationTypes[] = [
  {
    id: 1,
    years: "2024-2025",
    title: "Bachelor Développement Web",
    institution: "MyDigitalSchool",
    location: "Nantes",
    description: "à compléter",
    skills: ["React & Next.js", "Javascript & TypeScript", "Node.js & Express", "Tailwind CSS"],
    achievements: ["Stage en développement chez Keendoo"],
  },
  {
    id: 2,
    years: "2022-2024",
    title: "Bachelor Cycle Web et Multimédia",
    institution: "MyDigitalSchool",
    location: "Nantes",
    description: "à compléter",
    skills: [
      "Développement web",
      "Gestion de projets",
      "Webdesign",
      "Design Graphique",
      "Marketing Digital",
      "Communication digitale",
      "Motion Design",
      "Photo/Vidéo",
    ],
    achievements: ["Stage en développement chez Floax"],
  },
  {
    id: 3,
    years: "2019-2022",
    title: "Bachelor Sage-femme",
    institution: "Haute École Francisco Ferrer",
    description: "à compléter",
    skills: [
      "Physiologie de la grossesse",
      "Puériculture",
      "Premiers secours",
      "Hygiène et Prophylaxie",
      "Soins infirmiers",
    ],
    achievements: [
      "Stage en maternité post-partum",
      "Soins post-partum",
      "Conseils allaitement",
      "Accompagnement soin bébés",
      "Gestion dossiers patients",
    ],
  },
  {
    id: 4,
    years: "2018-2019",
    title: "PACES",
    institution: "Faculté de Médecine Henri Warembourg",
    location: "Lille",
    description: "Première Année Commune aux Études de Santé",
    skills: [
      "Anatomie",
      "Sciences humaines et sociales",
      "Biologie cellulaire",
      "Histologie-Embryologie",
      "Chimie/Biochimie",
      "Biostatistiques",
    ],
  },
  {
    id: 5,
    years: "2014-2018",
    title: "Baccalauréat Général Scientifique",
    institution: "Institution Sainte-Claire",
    location: "Lille",
    skills: ["Spécialité SVT"],
  },
];
